import "dotenv/config";

const PORT = process.env.PORT;
const GOOGLE_MAPS_API_KEY = process.env.GOOGLE_MAPS_API_KEY;
const NODE_ENV = process.env.NODE_ENV;
const RATE_LIMIT_MAX = process.env.RATE_LIMIT_MAX;
const RATE_LIMIT_TIME_WINDOW = process.env.RATE_LIMIT_TIME_WINDOW;
const ADMIN_EMAIL = process.env.ADMIN_EMAIL;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const GOOGLE_PLACES_API_KEY = process.env.GOOGLE_PLACES_API_KEY;

export {
  PORT,
  GOOGLE_MAPS_API_KEY,
  GOOGLE_PLACES_API_KEY,
  NODE_ENV,
  RATE_LIMIT_MAX,
  RATE_LIMIT_TIME_WINDOW,
  ADMIN_EMAIL,
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY,
};
